### ISSUE TITLE
Inconsistent definition of IDs

### ISSUE THREAD

**Issue by oberstet** [wamp-proto/wamp-proto#270]
From the mailing list: "request IDs are listed as being sequential in the section that describes ID scopes but described as "random" in the message descriptions."

**Comment by oberstet** [comment]
dup: https://github.com/wamp-proto/wamp-proto/issues/231

**Comment by gammazero** [comment]
This is still incorrect in the message description.  For example, here:
https://github.com/wamp-proto/wamp-proto/blob/master/rfc/text/basic/bp_rpc_calling_and_invocation.md

For **Call** it says,

> Request is a random, ephemeral ID chosen by the Caller and used to correlate the Dealer's response with the request.

I can create a PR to fix this.  Proposed wording:

```
Request is a sequential ID in the _session scope_, incremented by the caller, that is used to correlate the Dealer's response with the request.
```

I would also make the equivalent change for other messages.

**Comment by oberstet** [comment]
@gammazero oh, right. the text is still buggy. this paragraph is correct: https://wamp-proto.org/_static/gen/wamp_latest.html#ids

if you have time, yeah, would be cool if you can work out a PR! obviously, this shouldn't trigger any discussions and could be merged asap

**Comment by oberstet** [comment]
fixed via above PR - thx @gammazero !

**Comment by codebrainz** [comment]
I was reading from the specs linked from [here](https://wamp-proto.org/spec.html) and they still have this confusing random stuff, or am I missing something? Maybe it's just a matter of kicking off a re-build from the markdown?

**Comment by oberstet** [comment]
@codebrainz yeah, sth seems broken with our automated rebuilding and deployment. let me check ..

**Comment by codebrainz** [comment]
I think also maybe 61a8b860314cb5b9376dabe470fe7206c007ad9d forgot to update the `bp_pubsub_subscribing_and_unsubscribing.md` file?

**Comment by oberstet** [comment]
alright, auto-deployment works again .. including cloudfront update now:

* https://s3.eu-central-1.amazonaws.com/wamp-proto.org/index.html
* https://wamp-proto.org/index.html

---

rgd https://github.com/wamp-proto/wamp-proto/blob/master/rfc/text/basic/bp_pubsub_subscribing_and_unsubscribing.md

=> yes, seems we forgot to fix that .. reopening this issue.

**Comment by codebrainz** [comment]
> alright, auto-deployment works again .. including cloudfront update now

It's still not updated here using those links even after disabling cache, does it need another commit to trigger it? I also noticed the [SVG logo](https://wamp-proto.org/_static/wamp_logo.svg) at the top of [here](https://wamp-proto.org/_static/gen/wamp_latest.html) seems to be broken.

**Comment by oberstet** [comment]
mmh, not sure, it works for me:

![Bildschirmfoto von 2019-08-19 08-32-04](https://user-images.githubusercontent.com/233340/63243882-21b80a80-c25c-11e9-88fc-297adb8fcfe3.png)

![Bildschirmfoto von 2019-08-19 08-32-58](https://user-images.githubusercontent.com/233340/63243887-27adeb80-c25c-11e9-900a-d8f2741a6ba8.png)

![Bildschirmfoto von 2019-08-19 08-33-55](https://user-images.githubusercontent.com/233340/63243897-2da3cc80-c25c-11e9-8a43-953d4776136e.png)

**Comment by oberstet** [comment]
![Bildschirmfoto von 2019-08-19 08-40-01](https://user-images.githubusercontent.com/233340/63244235-20d3a880-c25d-11e9-99c8-9eb5c647dae0.png)

![Bildschirmfoto von 2019-08-19 08-41-06](https://user-images.githubusercontent.com/233340/63244244-26c98980-c25d-11e9-8cf0-6e75709ecfeb.png)

**Comment by codebrainz** [comment]
Weird, still not working here in Western Canada.
